spring:
    application:
        name: distributed-service

    datasource:
        # MySQL ?? ??
        url: jdbc:mysql://localhost:3306/music_share?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: music_user
        password: star15321!

    jpa:
        # Hibernate ??
        hibernate:
            ddl-auto: update    # ???? ? validate? ?? ??
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    redis:
        # Redis ?? ??
        host: localhost
        port: 6379

# JWT ?? ??
jwt:
    secret: YmFja2VuZF9zZWNyZXRfZm9yX2p3dF9hbmRfcmVmcmVzaF9zZWN1cml0eV9rZXkzMjMyMzIz
    expiration: 3600000              # Access Token ???? (1??)
    refresh-expiration: 1209600000   # Refresh Token ???? (2?)

#  ?? ?? ??
server:
    port: 8080